export default {
  'common.no': 'Ne',
  'common.yes': 'Ano',
  'common.cancel': 'Zrušit',
  'common.close': 'Zavřít',
  'common.share': 'Sdílet',
  'common.confirm': 'Potvrdit',
  'common.next': 'Dále',
  'common.back': 'Zpět',
  'common.save': 'Uložit',
  'common.saving': 'Ukládám ...',
  'common.saved': 'Uloženo',
  'common.loading': 'Načítání',
  'common.accept': 'Přijmout',
  'common.decline': 'Odmítnout',
  'common.tryAgain': 'Zkusit znovu',
  'common.loadingError': 'Ouha, data se nepodařilo načíst',
  'common.deletedError': 'Ouha, data se nepodařilo načíst, protože neukládáme smazané soubory.',
};
