export default {
  'common.no': 'No',
  'common.yes': 'Yes',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.share': 'Share',
  'common.confirm': 'Confirm',
  'common.next': 'Next',
  'common.back': 'Back',
  'common.save': 'Save',
  'common.saving': 'Saving ...',
  'common.saved': 'Saved',
  'common.loading': 'Loading',
  'common.tryAgain': 'Try again',
  'common.deletedError': 'Ouh, data was not loaded, because we don\'t save deleted files.',
  'common.loadingError': 'Damn, data was not loaded',
  'common.accept': 'Accept',
  'common.decline': 'Decline',
};
